[package]
name = "desktop-pet"
version = "0.1.0"
description = "Desktop Pet"
authors = ["wen <1911542586@qq.com>"]
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serialport = "4.2.0"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
msedge-tts = "0.4"
base64 = "0.23.0"
sysinfo = "0.39"
ureq = { version = "2.12", default-features = false, features = ["tls", "json"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Devices_Enumeration",
    "Foundation",
    "Foundation_Collections",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Properties",
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_System_Com",
    "Win32_System_Performance",
    "Win32_System_Registry",
    "Win32_System_SystemInformation",
    "Win32_System_WinRT",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.release.package.wry]
# debug = true
