import type { InjectionKey, Ref, ComputedRef } from "vue";
import type { PetModelKind } from "@/pet/skins";
import type { PetPersonality } from "@/pet/content/dialogue/personality";
import type { PetTone } from "@/pet/data/types";
import type { CustomVrmMotion } from "@/pet/content/motion/customVrmMotions";
import type { PetCustomLine } from "@/pet/content/dialogue/customLines";
import type { AppUiTheme } from "@/theme/uiTheme";

export type PetSettingsPageCtx = {
  enabled: Ref<boolean>;
  muted: Ref<boolean>;
  ttsEnabled: Ref<boolean>;
  ttsVoiceUri: Ref<string>;
  chatEnabled: Ref<boolean>;
  chatAiProvider: Ref<import("@/pet/chat/providers").PetChatProviderId>;
  chatAiApiKey: Ref<string>;
  chatAiBaseUrl: Ref<string>;
  chatAiModel: Ref<string>;
  chatAiCustomModels: Ref<string[]>;
  opacityPercent: Ref<number>;
  zoomPercent: Ref<number>;
  tone: Ref<PetTone>;
  demoMotion: Ref<string>;
  modelKind: Ref<PetModelKind>;
  lookId: Ref<string>;
  nickname: Ref<string>;
  personality: Ref<PetPersonality>;
  usbWatchEnabled: Ref<boolean>;
  randomIdleEnabled: Ref<boolean>;
  playfulModeEnabled: Ref<boolean>;
  hitBoundsEnabled: Ref<boolean>;
  catchphrases: Ref<string[]>;
  catchphraseChance: Ref<number>;
  uiTheme: Ref<AppUiTheme>;
  settingsAlwaysOnTop: Ref<boolean>;
  sysStatsDefaultExpanded: Ref<boolean>;
  customVrmMotions: Ref<CustomVrmMotion[]>;
  customLines: Ref<PetCustomLine[]>;
  customLinesOnly: Ref<boolean>;
  disabledMotions: Ref<string[]>;
  disabledBuiltInLines: Ref<string[]>;
  editingCustomId: Ref<string | null>;
  previewAutoOrbit: Ref<boolean>;
  canPreviewOrbit: ComputedRef<boolean>;
  vrmModelName: Ref<string>;
  vrmBusy: Ref<boolean>;
  isVrmPending: ComputedRef<boolean>;
  looks: ComputedRef<
    Array<{
      id: string;
      nameKey: string;
      toonNameKey?: string;
      figArtId?: string;
      visual: { accent: string; accentSoft: string };
    }>
  >;
  formOptions: ComputedRef<Array<{ label: string; value: PetModelKind }>>;
  formPickerRef: Ref<HTMLElement | null>;
  formThumbStyle: Ref<Record<string, string>>;
  toneOptions: ComputedRef<Array<{ label: string; value: string }>>;
  ttsVoiceOptions: Ref<Array<{ label: string; value: string }>>;
  personalityOptions: ComputedRef<Array<{ label: string; value: string }>>;
  uiThemeOptions: ComputedRef<Array<{ label: string; value: string }>>;
  motionOptions: ComputedRef<Array<{ label: string; value: string }>>;
  motionPoolIds: ComputedRef<string[]>;
  skinDefaultNickname: ComputedRef<string>;
  capabilities: ComputedRef<Set<import("@/pet/characters").PetCapability>>;
  lookLabel: (theme: { nameKey: string; toonNameKey?: string }) => string;
  onEnabled: (v: boolean) => void | Promise<void>;
  onModel: (v: string | number) => void | Promise<void>;
  onLook: (id: string) => void | Promise<void>;
  onSaveNickname: () => void | Promise<void>;
  onPersonality: (v: string | number) => void | Promise<void>;
  onResetProfile: () => void | Promise<void>;
  onMuted: (v: boolean) => void | Promise<void>;
  onTtsEnabled: (v: boolean) => void | Promise<void>;
  onTtsVoice: (v: unknown) => void | Promise<void>;
  onChatEnabled: (v: boolean) => void | Promise<void>;
  onChatAiProvider: (v: unknown) => void;
  onChatAiModel: (v: unknown) => void;
  onChatAiAddModel: () => void;
  onChatAiRemoveModel: (id: string) => void;
  onChatAiSave: () => void | Promise<void>;
  onChatAiReset: () => void;
  chatAiDirty: ComputedRef<boolean>;
  canAddChatAiModel: ComputedRef<boolean>;
  onOpacity: (v: number) => void | Promise<void>;
  onZoom: (v: number) => void | Promise<void>;
  resetOpacity: () => void | Promise<void>;
  resetZoom: () => void | Promise<void>;
  onTone: (v: string | number) => void | Promise<void>;
  onUsbWatch: (v: boolean) => void | Promise<void>;
  onRandomIdle: (v: boolean) => void | Promise<void>;
  onPlayfulMode: (v: boolean) => void | Promise<void>;
  onHitBounds: (v: boolean) => void | Promise<void>;
  onPickVrm: () => void | Promise<void>;
  onClearVrm: () => void | Promise<void>;
  onDemoMotion: (v: unknown) => void | Promise<void>;
  onPlayMotion: () => void | Promise<void>;
  onUiTheme: (v: unknown) => void | Promise<void>;
  onSettingsPin: (v: unknown) => void | Promise<void>;
  onSysStatsDefaultExpanded: (v: unknown) => void | Promise<void>;
  persistOnly: () => void | Promise<void>;
  persistCustomMotions: () => void | Promise<void>;
  onAddCustomMotion: () => void | Promise<void>;
  toggleEditCustom: (id: string) => void;
  onCustomMotionBoneChange: (m: CustomVrmMotion) => void;
  onRemoveCustomMotion: (id: string) => void | Promise<void>;
  onPlayCustomMotion: (id: string) => void | Promise<void>;
};

export const PET_SETTINGS_PAGE_KEY: InjectionKey<PetSettingsPageCtx> =
  Symbol("pet-settings-page");
