import type { InjectionKey, Ref, ComputedRef } from "vue";
import type { PetModelKind } from "@/pet/skins";
import type { PetPersonality } from "@/pet/content/dialogue/personality";
import type { PetTone } from "@/pet/data/types";
import type { CustomVrmMotion } from "@/pet/content/motion/customVrmMotions";
import type { PetCustomLine } from "@/pet/content/dialogue/customLines";
import type { PetThemeSettings } from "@/theme/types";

export type PetSettingsPageCtx = {
  enabled: Ref<boolean>;
  muted: Ref<boolean>;
  ttsEnabled: Ref<boolean>;
  ttsVoiceUri: Ref<string>;
  chatEnabled: Ref<boolean>;
  chatAiProvider: Ref<import("@/pet/chat/providers").PetChatProviderId>;
  chatAiApiKey: Ref<string>;
  chatAiBaseUrl: Ref<string>;
  chatAiModel: Ref<string>;
  chatAiCustomModels: Ref<string[]>;
  opacityPercent: Ref<number>;
  zoomPercent: Ref<number>;
  tone: Ref<PetTone>;
  demoMotion: Ref<string>;
  modelKind: Ref<PetModelKind>;
  lookId: Ref<string>;
  nickname: Ref<string>;
  personality: Ref<PetPersonality>;
  usbWatchEnabled: Ref<boolean>;
  randomIdleEnabled: Ref<boolean>;
  playfulModeEnabled: Ref<boolean>;
  hitBoundsEnabled: Ref<boolean>;
  deskWeather: Ref<import("@/pet/data/deskWeather").DeskWeatherConfig>;
  skyWeather: Ref<import("@/pet/data/skyWeather").SkyWeatherConfig>;
  catchphrases: Ref<string[]>;
  catchphraseChance: Ref<number>;
  theme: Ref<PetThemeSettings>;
  settingsAlwaysOnTop: Ref<boolean>;
  sysStatsDefaultExpanded: Ref<boolean>;
  customVrmMotions: Ref<CustomVrmMotion[]>;
  customLines: Ref<PetCustomLine[]>;
  customLinesOnly: Ref<boolean>;
  disabledMotions: Ref<string[]>;
  disabledBuiltInLines: Ref<string[]>;
  editingCustomId: Ref<string | null>;
  previewAutoOrbit: Ref<boolean>;
  canPreviewOrbit: ComputedRef<boolean>;
  vrmModelName: Ref<string>;
  vrmBusy: Ref<boolean>;
  isVrmPending: ComputedRef<boolean>;
  looks: ComputedRef<
    Array<{
      id: string;
      nameKey: string;
      toonNameKey?: string;
      figArtId?: string;
      visual: { accent: string; accentSoft: string };
    }>
  >;
  formOptions: ComputedRef<Array<{ label: string; value: PetModelKind }>>;
  formPickerRef: Ref<HTMLElement | null>;
  formThumbStyle: Ref<Record<string, string>>;
  toneOptions: ComputedRef<Array<{ label: string; value: string }>>;
  ttsVoiceOptions: Ref<Array<{ label: string; value: string }>>;
  personalityOptions: ComputedRef<Array<{ label: string; value: string }>>;
  themeStageModeOptions: ComputedRef<Array<{ label: string; value: string }>>;
  themeWallpaperFitOptions: ComputedRef<Array<{ label: string; value: string }>>;
  bootDurationModeOptions: ComputedRef<Array<{ label: string; value: string }>>;
  motionOptions: ComputedRef<Array<{ label: string; value: string }>>;
  motionPoolIds: ComputedRef<string[]>;
  skinDefaultNickname: ComputedRef<string>;
  capabilities: ComputedRef<Set<import("@/pet/characters").PetCapability>>;
  lookLabel: (look: { nameKey: string; toonNameKey?: string }) => string;
  onEnabled: (v: boolean) => void | Promise<void>;
  onModel: (v: string | number) => void | Promise<void>;
  onLook: (id: string) => void | Promise<void>;
  onSaveNickname: () => void | Promise<void>;
  onPersonality: (v: string | number) => void | Promise<void>;
  onResetProfile: () => void | Promise<void>;
  onFactoryReset: () => void;
  onClearCache: () => void | Promise<void>;
  onMuted: (v: boolean) => void | Promise<void>;
  onTtsEnabled: (v: boolean) => void | Promise<void>;
  onTtsVoice: (v: unknown) => void | Promise<void>;
  onChatEnabled: (v: boolean) => void | Promise<void>;
  onChatAiProvider: (v: unknown) => void;
  onChatAiModel: (v: unknown) => void;
  onChatAiAddModel: () => void;
  onChatAiRemoveModel: (id: string) => void;
  onChatAiSave: () => void | Promise<void>;
  onChatAiReset: () => void;
  chatAiDirty: ComputedRef<boolean>;
  canAddChatAiModel: ComputedRef<boolean>;
  onOpacity: (v: number) => void | Promise<void>;
  onZoom: (v: number) => void | Promise<void>;
  resetOpacity: () => void | Promise<void>;
  resetZoom: () => void | Promise<void>;
  onTone: (v: string | number) => void | Promise<void>;
  onUsbWatch: (v: boolean) => void | Promise<void>;
  onRandomIdle: (v: boolean) => void | Promise<void>;
  onPlayfulMode: (v: boolean) => void | Promise<void>;
  onHitBounds: (v: boolean) => void | Promise<void>;
  onDeskWeatherChange: () => void | Promise<void>;
  onSkyWeatherChange: () => void | Promise<void>;
  /** 窗景 tab 与预览旁芯片共用 */
  patchSkyWeather: (
    partial: Partial<import("@/pet/data/skyWeather").SkyWeatherConfig>
  ) => void;
  onSkyEnableOnPet: (on: boolean) => void;
  onSkyBgOpacity: (v: number) => void;
  resetSkyBgOpacity: () => void;
  /** 与预览旁芯片同一计算源 */
  skyBgOpacityPercent: ComputedRef<number>;
  /** 跟随系统解析城；探测/同步 busy；联网探测是否成功 */
  skyNetCityId: Ref<string>;
  skyNetBusy: Ref<boolean>;
  skyNetBadgeOnline: Ref<boolean>;
  /** 强制探测联网；天气系统切在线前用 */
  probeSkyNet: () => Promise<boolean>;
  /** 当前展示天色/天气（驱动行旁提示） */
  skyDisplayTod: Ref<import("@/pet/data/skyWeather").SkyTodId>;
  skyDisplayWeather: Ref<import("@/pet/data/skyWeather").SkyWeatherId>;
  onPickVrm: () => void | Promise<void>;
  onClearVrm: () => void | Promise<void>;
  onDemoMotion: (v: unknown) => void | Promise<void>;
  onPlayMotion: () => void | Promise<void>;
  onThemeStyle: (v: unknown) => void | Promise<void>;
  onThemeStageMode: (v: unknown) => void | Promise<void>;
  onThemeWallpaperDim: (v: unknown) => void | Promise<void>;
  onBubbleOpacity: (v: unknown) => void | Promise<void>;
  onThemeWallpaperFit: (v: unknown) => void | Promise<void>;
  onPickThemeWallpaper: () => void | Promise<void>;
  onClearThemeWallpaper: () => void | Promise<void>;
  onThemeWallpaperMuted: (v: unknown) => void | Promise<void>;
  onBootAnimationEnabled: (v: unknown) => void | Promise<void>;
  onBootAnimationMuted: (v: unknown) => void | Promise<void>;
  onBootAnimationFit: (v: unknown) => void | Promise<void>;
  onPickBootAnimation: () => void | Promise<void>;
  onClearBootAnimation: () => void | Promise<void>;
  onBootAnimationDurationMode: (v: unknown) => void | Promise<void>;
  onBootAnimationDurationSec: (v: unknown) => void | Promise<void>;
  onSettingsPin: (v: unknown) => void | Promise<void>;
  onSysStatsDefaultExpanded: (v: unknown) => void | Promise<void>;
  persistOnly: () => void | Promise<void>;
  persistCustomMotions: () => void | Promise<void>;
  onAddCustomMotion: () => void | Promise<void>;
  toggleEditCustom: (id: string) => void;
  onCustomMotionBoneChange: (m: CustomVrmMotion) => void;
  onRemoveCustomMotion: (id: string) => void | Promise<void>;
  onPlayCustomMotion: (id: string) => void | Promise<void>;
};

export const PET_SETTINGS_PAGE_KEY: InjectionKey<PetSettingsPageCtx> =
  Symbol("pet-settings-page");
